### PR TITLE
multi releay in one command

### PR DESCRIPTION
**Pull request by honwen**
inspire of https://docs.ginuerzh.xyz/gost/port-forwarding/

### CODE REVIEW

**Comment by honwen** [comment]
also maybe make it easiler to configure split `TCP/UDP` in the future

```bash
./realm --tcp=127.0.0.1:30000/example.com:12345 --udp=127.0.0.1:40000/example.com:23456
```

**Comment by zhboner** [comment]
Hi @honwen , 

Thanks for your PR. I really appreciate your contribution.

However, the support of multi relay in one command complicates the use of Realm. Currently, realm supports config file, so if you want multiple relays in one process, you can simply write a config file to achieve it. 

Having said that, I am open for PRs for any potential improvements to realm and looking forward to your future contribution. Thank you.

**Comment by honwen** [comment]
this PR is required to split `TCP/UDP`, does this repo need this feature?

**Comment by zephyrchien** [comment]
I think it is a good point to split TCP/UDP, since UDP is seldom used. 

I would like to keep the command line simple, and pay more efforts to improve the config file(for example, add a new option to enable/disable UDP. Actually I think the config file part should be refactored..).

**Pull request closed without merging**
